bt_navigator:
  ros__parameters:
    use_sim_time: false
    global_frame: map
    robot_base_frame: base_footprint
    odom_topic: /roverlad_controller/odom
    transform_tolerance: 0.3
    default_server_timeout: 1000
    bt_loop_duration: 10
    wait_for_service_timeout: 1000
    default_nav_to_pose_bt_xml: "/home/jetsonalex/Roverlad_ROS2/src/roverlad_navigation/bt/simple_navigation_w_replanning.xml"
    default_nav_through_poses_bt_xml: "/home/jetsonalex/Roverlad_ROS2/src/roverlad_navigation/bt/simple_navigation_w_replanning.xml"